apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname', 'job', 'instance', 'mountpoint', 'pod', 'namespace']

      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

      receiver: discord

    receivers:
    - name: discord
      discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1374798725997924362/AGTOnlIS4Yx_RkJArszM6R5SAPCu4UAFS5vH2t2hKFSBnsLpyJLqPog9nBTps9d6oMZx
        message: |
          🔔 **Alerta Prometheus**
          🚨 *{{ .CommonAnnotations.summary }}*
          
          🔹 **Status**: {{ .Status }}
          🔹 **Alerta**: {{ .CommonLabels.alertname }}
          🔹 **Severidade**: {{ .CommonLabels.severity }}
          🔹 **Descrição**: {{ .CommonAnnotations.description }}
          🔹 **Fonte**: https://alertmanager-hml.jetsales.com.br/